name = "cloud-notepad"
main = "src/index.js"
compatibility_date = "2022-05-13"

kv_namespaces = [
  { binding = "NOTES", id = "bdce957363ef47379028936feb2e557e" },
  { binding = "SHARE", id = "90239213f71f4c618021b0d65f82c371" }
]